name: build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux:
    if: 1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Source Code
        run: |
          lscpu
          echo $PATH
          env
          docker info
          id -u
          id -g
          who
          cat /etc/os-release
          hostnamectl
          uname -s
          uname -m
          uname -r
          node -v

      - name: Build
        run: |
          bash  release-archive.sh
          bash  release-archive-v3.sh
          ls -lah dist

      - name: production artifacts v2
        uses: actions/upload-artifact@v4
        with:
          name: replace-google-cdn-v2
          retention-days: 90
          path: |
            dist/ReplaceGoogleCDN-v2.zip

      - name: production artifacts v3
        uses: actions/upload-artifact@v4
        with:
          name: replace-google-cdn-v3
          retention-days: 7
          path: |
            dist/ReplaceGoogleCDN-v3.zip

      - name: production artifacts v3 chromium
        uses: actions/upload-artifact@v4
        with:
          name: replace-google-cdn-v3-chromium
          retention-days: 7
          path: |
            dist/ReplaceGoogleCDN-v3-chromium.zip

      - name: production artifacts v3 firefox
        uses: actions/upload-artifact@v4
        with:
          name: replace-google-cdn-v3-firefox
          retention-days: 7
          path: |
            dist/ReplaceGoogleCDN-v3-firefox.zip

      - name: Release
        uses: softprops/action-gh-release@v2.0.8
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/ReplaceGoogleCDN-v2.zip
            dist/ReplaceGoogleCDN-v3.zip
            dist/ReplaceGoogleCDN-v3-chromium.zip
            dist/ReplaceGoogleCDN-v3-firefox.zip

      - name: Browser Plugin Publish v2
        if: 0
        uses: PlasmoHQ/bpp@v2
        with:
          artifact: "dist/ReplaceGoogleCDN-v2.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}

      - name: Browser Plugin Publish v3
        if: 0
        uses: PlasmoHQ/bpp@v3
        with:
          artifact: "dist/ReplaceGoogleCDN-v3.zip"
          keys: ${{ secrets.SUBMIT_KEYS }}
        # 使用参考 https://github.com/PlasmoHQ/bpp.git
