name: windows-x86_64

on: [push, pull_request]

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  windows:
    if: 1
    runs-on: windows-latest
    steps:
      - name: Prepare git
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
          env
          ipconfig
          uname -a
          pwd
          ipconfig /all

      - uses: actions/checkout@v4
      - name: Prepare Chromium Run Environment
        run: |
          ipconfig /all

      - name: Cache Chromium
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}\var\chrome-win.zip
            ${{ github.workspace }}\var\chrome-win
          key: ${{ runner.os }}-x86_64-chromium

      - name: Download Chromium
        shell: bash
        run: |
          set -x
          if [ ! -f var/chrome-win.zip ] ; then
            bash tools/download-chromium.sh
          fi

      - name: Cache Firefox
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}\var\firefox.exe
          key: ${{ runner.os }}-x86_64-firefox

      - name: Download Firefox
        shell: bash
        run: |
          set -x
          if [ ! -f var/firefox.exe ] ; then
            bash tools/download-firefox.sh
          fi

      - name: install firefox
        shell: cmd
        run: |
          DIR
          ECHO %CD%

          :: msiexec /package /qn  "%CD%\var\firefox.msi"
          :: var\firefox.exe /?
          :: start var\firefox.exe /S

          ::  静默安装 firefox
          var\firefox.exe /A /S
          timeout /T 30 /NOBREAK

          :: show firefox install directory
          DIR "C:\Program Files\Mozilla Firefox"

          :: show firefox version
          "C:\Program Files\Mozilla Firefox\firefox.exe" --version

      - name: show browser version
        shell: cmd
        run: |
          DIR var
          :: var\chrome-win\chrome.exe --version
          "C:\Program Files\Mozilla Firefox\firefox.exe" --version

        # https://www.msys2.org/docs/ci/
        # https://github.com/marketplace/actions/setup-msys2
      #      - uses: msys2/setup-msys2@v2
      #        with:
      #          msystem: UCRT64
      #          update: false
      #          install: git mingw-w64-ucrt-x86_64-gcc
      #
      #      - name: CI-Build
      #        shell: msys2 {0}
      #        run: |
      #          echo 'Running in MSYS2!'
      #
      #          echo "C:\\msys64\\usr\\bin" >> $GITHUB_PATH
      #          echo "C:\\msys64\\mingw64\\bin" >> $GITHUB_PATH
      #          echo "PKG_CONFIG_PATH=/mingw64/lib/pkgconfig" >> $GITHUB_ENV
      #
      #      - name: test powershell use msys2
      #        shell: powershell
      #        run: msys2 -c 'uname -a'
      #
      #      - name: test cmd use msys2
      #        shell: cmd
      #        run: msys2 -c 'uname -a'

      - name: Test
        shell: cmd
        run: |
          REM change CHCP to UTF-8
          @chcp 65001>nul
          echo foo=bar >> %GITHUB_OUTPUT%
